### ISSUE TITLE
I have issue with my internet connection

### ISSUE THREAD

**Issue by UndoubtedlyMAD** [vanishedvan/vanishedvan#1]
Please fix internet connection, I have hear that they say "The internet is vanished" so I come to you today to ask you please give me my internet back. I will sell my wife for your services, I am JFK big man, I came back from a mind blowing experience, and I wanted to get internet the new thing from 1995 Dial Up, please fix you are services. Thank you, very mucho gracias.
You'res truly, 
Jevgeni Fuckyou Kabancowa

**Comment by pauleks** [comment]
. 　　　。　　　　•　 　ﾟ　　。 　　.

　　　.　　　 　　.　　　　　。　　 。　. 　

.　　 。　　　　　 ඞ 。 . 　　 • 　　　　•

　　ﾟ　　 Red was not An Impostor.　 。　.

　　'　　　 1 Impostor remains 　 　　。

　　ﾟ　　　.　　　. ,　　　　.　 .

**Comment by UndoubtedlyMAD** [comment]
Please fix as soon as possible, I need to contact my family again. They are far away abroad in a country called "Heaven", I don't know what "Heaven" country is, but please give internet so I can visit family, or I will go back to how I was in 1963. 
Thank you again very thank you,
Yes

**Comment by UndoubtedlyMAD** [comment]
> . 　　　。　　　　•　 　ﾟ　　。 　　.
> 
> 　　　.　　　 　　.　　　　　。　　 。　. 　
> 
> .　　 。　　　　　 ඞ 。 . 　　 • 　　　　•
> 
> 　　ﾟ　　 Red was not An Impostor.　 。　.
> 
> 　　'　　　 1 Impostor remains 　 　　。
> 
> 　　ﾟ　　　.　　　. ,　　　　.　 .

Are you one of the Tech Support? Because I don't understand this language, please give me more information about how to fix my Dial Up internation connation

**Comment by pauleks** [comment]
> 
> 
> > . 　　　。　　　　•　 　ﾟ　　。 　　.
> > 　　　.　　　 　　.　　　　　。　　 。　. 　
> > .　　 。　　　　　 ඞ 。 . 　　 • 　　　　•
> > 　　ﾟ　　 Red was not An Impostor.　 。　.
> > 　　'　　　 1 Impostor remains 　 　　。
> > 　　ﾟ　　　.　　　. ,　　　　.　 .
> 
> Are you one of the Tech Support? Because I don't understand this language, please give me more information about how to fix my Dial Up internation connation

Ｉ ａｃｃｉｄｅｎｔａｌｌｙ ｄｏｗｎｌｏａｄｅｄ ａ ｖｉｒｕｓ ａｎｄ ｎｏｗ Ｉ ｃａｎ ｏｎｌｙ ｗｒｉｔｅ ｉｎ ＷＩＤＥ ＬＡＴＩＮ ａｎｄ ａｌｓｏ ｗｈｅｎｅｖｅｒ Ｉ ｔｙｐｅ ＷＩＤＥ ＬＡＴＩＮ ｉｔ ａｕｔｏｍａｔｉｃａｌｌｙ ｇｅｔｓ ｃａｐｉｔａｌｉｚｅｄ ｈｅｌｐ

**Comment by UndoubtedlyMAD** [comment]
> > > . 　　　。　　　　•　 　ﾟ　　。 　　.
> > > 　　　.　　　 　　.　　　　　。　　 。　. 　
> > > .　　 。　　　　　 ඞ 。 . 　　 • 　　　　•
> > > 　　ﾟ　　 Red was not An Impostor.　 。　.
> > > 　　'　　　 1 Impostor remains 　 　　。
> > > 　　ﾟ　　　.　　　. ,　　　　.　 .
> > 
> > 
> > Are you one of the Tech Support? Because I don't understand this language, please give me more information about how to fix my Dial Up internation connation
> 
> Ｉ ａｃｃｉｄｅｎｔａｌｌｙ ｄｏｗｎｌｏａｄｅｄ ａ ｖｉｒｕｓ ａｎｄ ｎｏｗ Ｉ ｃａｎ ｏｎｌｙ ｗｒｉｔｅ ｉｎ ＷＩＤＥ ＬＡＴＩＮ ａｎｄ ａｌｓｏ ｗｈｅｎｅｖｅｒ Ｉ ｔｙｐｅ ＷＩＤＥ ＬＡＴＩＮ ｉｔ ａｕｔｏｍａｔｉｃａｌｌｙ ｇｅｔｓ ｃａｐｉｔａｌｉｚｅｄ ｈｅｌｐ

I will report you to the Fucking Bureau of Incestigation, please give more information or you will go to FBI!!!
Your are truly,
JKFC

**Comment by ibrahimcaj** [comment]
Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.

**Comment by UndoubtedlyMAD** [comment]
> Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.

I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
So you are lie, and you are blyat, you you, you you are you 
Thanks you

**Comment by ibrahimcaj** [comment]
> > Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.
> 
> I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
> So you are lie, and you are blyat, you you, you you are you
> Thanks you

Sir, that is a big lie. I have your IP address, which I got from your computer your computer. I know that you live in Liberia, this is your house 
![image](https://user-images.githubusercontent.com/32491163/108890143-7c7ab100-760d-11eb-8204-05aa93f30c58.png)

**Comment by UndoubtedlyMAD** [comment]
> > > Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.
> > 
> > 
> > I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
> > So you are lie, and you are blyat, you you, you you are you
> > Thanks you
> 
> Sir, that is a big lie. I have your IP address, which I got from your computer your computer. I know that you live in Liberia, this is your house
> ![image](https://user-images.githubusercontent.com/32491163/108890143-7c7ab100-760d-11eb-8204-05aa93f30c58.png)

If I living in Liberia, I wouldn't be asking you for you are support, you are America scum you mother go in you you are!

**Comment by ibrahimcaj** [comment]
> > > > Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.
> > > 
> > > 
> > > I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
> > > So you are lie, and you are blyat, you you, you you are you
> > > Thanks you
> > 
> > 
> > Sir, that is a big lie. I have your IP address, which I got from your computer your computer. I know that you live in Liberia, this is your house
> > ![image](https://user-images.githubusercontent.com/32491163/108890143-7c7ab100-760d-11eb-8204-05aa93f30c58.png)
> 
> If I living in Liberia, I wouldn't be asking you for you are support, you are America scum you mother go in you you are!

Sir, I am already inside of your mother.

**Comment by UndoubtedlyMAD** [comment]
> > > > > Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.
> > > > 
> > > > 
> > > > I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
> > > > So you are lie, and you are blyat, you you, you you are you
> > > > Thanks you
> > > 
> > > 
> > > Sir, that is a big lie. I have your IP address, which I got from your computer your computer. I know that you live in Liberia, this is your house
> > > ![image](https://user-images.githubusercontent.com/32491163/108890143-7c7ab100-760d-11eb-8204-05aa93f30c58.png)
> > 
> > 
> > If I living in Liberia, I wouldn't be asking you for you are support, you are America scum you mother go in you you are!
> 
> Sir, I am already inside of your mother.

Sir, my mother is in grave, so you are in grave? Is my mother doing okay in her new house? She said she don't want good home so she decided to live there instead 
Please thanks for information, but don't be inside mother too much cause she is very old and bones are very not good!
You are thank you, you 
Jevgeni

**Comment by ibrahimcaj** [comment]
> > > > > > Hello Mr. JFK man. I am very happy that you have contacted us. We sadly have to let you know that your wife is with me, and we get freaky every night. 😈 Also, your internet is very bad because you did not pay your bills since 22nd of November, 1963, at 12:30 PM.
> > > > > 
> > > > > 
> > > > > I am the presidential palace of the United Arab Emirates of America! Also, my woman is called Jekatrina, and she is woman that has no woman you are.
> > > > > So you are lie, and you are blyat, you you, you you are you
> > > > > Thanks you
> > > > 
> > > > 
> > > > Sir, that is a big lie. I have your IP address, which I got from your computer your computer. I know that you live in Liberia, this is your house
> > > > ![image](https://user-images.githubusercontent.com/32491163/108890143-7c7ab100-760d-11eb-8204-05aa93f30c58.png)
> > > 
> > > 
> > > If I living in Liberia, I wouldn't be asking you for you are support, you are America scum you mother go in you you are!
> > 
> > 
> > Sir, I am already inside of your mother.
> 
> Sir, my mother is in grave, so you are in grave? Is my mother doing okay in her new house? She said she don't want good home so she decided to live there instead
> Please thanks for information, but don't be inside mother too much cause she is very old and bones are very not good!
> You are thank you, you
> Jevgeni

Sir, don't worry. She is now better than ever before, I have closed the grave just like nothing happened. 
Is your internet still working sir? Me being in your mother should have fixed it.
